if (MSVC)
if(OpenCV_FOUND)
	set(JPEG_ENCODER EncoderWIC)
	set(PNG_ENCODER EncoderCvPNG)
else()
	set(JPEG_ENCODER EncoderSTBJPG)
	set(PNG_ENCODER EncoderSTBPNG)
endif()
else()
if(OpenCV_FOUND)
	set(JPEG_ENCODER EncoderCvJPG)
	set(PNG_ENCODER EncoderCvPNG)
else()
	set(JPEG_ENCODER EncoderSTBJPG)
	set(PNG_ENCODER EncoderSTBPNG)
endif()
endif()

add_library(phy_encoder OBJECT stb_image_write.c Encoder.cpp)
target_link_libraries(phy_encoder PUBLIC yuv)
target_compile_definitions(phy_encoder PUBLIC JPEG_ENCODER=${JPEG_ENCODER} PNG_ENCODER=${PNG_ENCODER} JPEG_ENCODER_HEADER="${JPEG_ENCODER}.hpp" PNG_ENCODER_HEADER="${PNG_ENCODER}.hpp")
target_include_directories(phy_encoder PUBLIC ${PROJECT_SOURCE_DIR}/libyuv/include/)

target_link_libraries(phy_encoder PUBLIC opencv_imgcodecs opencv_core)
target_include_directories(phy_encoder PUBLIC ./  ${CMAKE_SOURCE_DIR}/src/utils)
target_compile_definitions(phy_encoder PRIVATE CPU_COUNT=${ProcessorCount_N})

add_executable(encoder_test EXCLUDE_FROM_ALL encoder_test.cc )
target_link_libraries(encoder_test PRIVATE ${OpenCV_LIBS} phy_encoder)
target_compile_definitions(encoder_test PRIVATE CPU_COUNT=${ProcessorCount_N})
