set(MSMF_REQ_LIBS mfplat mf mfuuid mfreadwrite Shlwapi strmiids)
set(MSMF_FOUND TRUE)
set(MSMF_LIBS)
foreach(LIB IN LISTS MSMF_REQ_LIBS)
	find_library(${LIB} NAMES  ${LIB} NO_CACHE)
	if(${LIB})
		list(APPEND MSMF_LIBS ${${LIB}})
	else()
		set(MSMF_FOUND FALSE)
		break()
	endif()
endforeach()